### PR TITLE
Deprecate the use of io.popen in most widget types

### LINKED ISSUE #74: Stop using io.popen
This is a forwarding of https://github.com/awesomeWM/awesome/issues/2697.

The short version: The volume widget uses `io.popen` to start `amixer`. For some unknown reason, `amixer` hangs(*). (Can be seen in the output of `pstree`: There is still an `amixer` process there.) As a result, all of AwesomeWM hangs.

Please use `awful.spawn.easy_async` instead.

(*) Well, or alternatively: For some weird reason, `amixer` exits, becomes a zombie (hence still shows up in `pstree`), but is not reaped via `pclose`. I'd need a backtrace for the awesome C code to see if is hung in reading `amixer`'s output or in the `pclose`, but I would expect that reading the output hangs.

CC @furgerf

### LINKED ISSUE #82: Deprecate the use of io.popen in widget types
This is a continuation of #74. TL;DR `io.popen` may hangs Awesome on IO-intensive process, `awful.spawn.{easy_async,with_line_callback}` are better, use them instead.

Since #74 was open with a specific context/linked with a specific bug, and I need a tracker for current progress of refactoring, this issue is opened with a list of all files currently using `io.popen`:

- [x] ~~spawn.lua~~ *this is the wrapper to fallback to `io.popen` when `awful.spawn` is not availble*
- [x] helpers.lua
- [x] widgets/bat_freebsd.lua
- [x] widgets/mem_freebsd.lua
- [x] widgets/bat_openbsd.lua
- [x] widgets/hwmontemp_linux.lua
- [x] widgets/mdir_all.lua
- [x] widgets/os_all.lua
- [x] widgets/net_freebsd.lua
- [x] widgets/wifiiw_linux.lua
- [x] widgets/wifi_linux.lua
- [x] widgets/mpd_all.lua
- [x] widgets/hddtemp_linux.lua
- [x] widgets/gmail_all.lua
- [x] widgets/fs_all.lua
- [x] widgets/volume_freebsd.lua
- [x] widgets/volume_linux.lua
- [ ] contrib/ossvol_linux.lua
- [ ] contrib/openweather_all.lua
- [ ] contrib/countfiles_all.lua
- [ ] contrib/pulse_all.lua
- [ ] contrib/mpc_all.lua
- [ ] contrib/buildbot_all.lua
- [ ] contrib/nvinf_all.lua
- [x] contrib/cmus_all.lua
- [ ] contrib/sensors_linux.lua
- [ ] contrib/rss_all.lua
- [ ] contrib/wpa_all.lua
- [ ] contrib/netcfg.lua
- [ ] contrib/nvsmi_all.lua

Since there are many widget types I cannot test, I will push changes to a new branch `async` and tick the completed ones.

### PR DESCRIPTION
**Pull request by McSinyx**
This should close #82 and close #74. Most contrib widget types is not converted to be async at the moment, since many are either broken or rely on an API that has changed.

~~This is meant to be review by other members of the org--afterwards these commits might need to be manually rebased.~~ Edit: conflicts were resolved.

### CODE REVIEW

**Comment by McSinyx** [comment]
@kiike can you please test the battery widget type on OpenBSD?

**Comment by kiike** [comment]
@McSinyx, pulled the async brach and the widget works perfectly fine. No issues encountered so far.

**Comment by McSinyx** [comment]
Thank you, it is great to know!

**Comment by mutlusun** [comment]
I tried to improve the documentation line of the sysctl_async function. To me, everything looks ready to merge. I am using the async branch for a couple of weeks now and didn't encounter any problems ... Thanks for your work!

File: widgets/bat_openbsd.lua [hunk 1]
```diff
@@ -1,67 +1,85 @@
...
+return helpers.setasyncall{
+    async = function (format, warg, callback)
+        local filter = "hw.sensors.acpi" .. (warg or "bat0")
+        local pattern = filter .. ".(%S+)=(%S+)"
+        local bat_info = {}
 
-    -- battery capacity in percent
-    local percent = tonumber(bat_info.watthour3 / bat_info.watthour0 * 100)
+        spawn.with_line_callback_with_shell(
+            ("sysctl -a | grep '^%s'"):format(filter),
```
Comment (mutlusun) [inline widgets/bat_openbsd.lua]: Maybe we can use here the sysctl_async function as well? I am not able to test this, so I don't touch this ...

Comment (McSinyx) [reply widgets/bat_openbsd.lua]: I suppose so, since it uses `string.gmatch`. I was blindly translating from `for line in proc:lines("*l")` I think. Using `spawn.async` make it a lot easier to read. @kiike could you please check if this patch works for you:

```diff
diff --git widgets/bat_openbsd.lua widgets/bat_openbsd.lua
index ced83d8..6718b9b 100644
--- widgets/bat_openbsd.lua
+++ widgets/bat_openbsd.lua
@@ -34,52 +34,49 @@ local STATES = { [0] = "↯",         -- not charging
 
 return helpers.setasyncall{
     async = function (format, warg, callback)
-        local filter = "hw.sensors.acpi" .. (warg or "bat0")
-        local pattern = filter .. ".(%S+)=(%S+)"
-        local bat_info = {}
+        if warg == nil then warg = 'bat0' end
+        local pattern = ("hw.sensors.acpi%s.(%S+)=(%S+)"):format(warg)
 
-        spawn.with_line_callback_with_shell(
-            ("sysctl -a | grep '^%s'"):format(filter),
-            { stdout = function (line)
-                  for key, value in line:gmatch(pattern) do
-                      bat_info[key] = value
-                  end
-              end,
-              output_done = function ()
-                  -- current state
-                  local state = STATES[tonumber(bat_info.raw0)]
+        spawn.async(
+            "sysctl -a",
+            function (stdout, stderr, exitreason, exitcode)
+                local bat_info = {}
+                for key, value in stdout:gmatch(pattern) do
+                    bat_info[key] = value
+                end
 
-                  -- battery capacity in percent
-                  local percent = tonumber(
-                      bat_info.watthour3 / bat_info.watthour0 * 100)
+                -- current state
+                local state = STATES[tonumber(bat_info.raw0)]
 
-                  local time
-                  if tonumber(bat_info.power0) < 1 then
-                      time = "∞"
-                  else
-                      local raw_time = bat_info.watthour3 / bat_info.power0
-                      local hours, hour_fraction = math.modf(raw_time)
-                      local minutes = math.floor(60 * hour_fraction)
-                      time = ("%d:%0.2d"):format(hours, minutes)
-                  end
+                -- battery capacity in percent
+                local percent = tonumber(
+                    bat_info.watthour3 / bat_info.watthour0 * 100)
 
-                  -- calculate wear level from (last full / design) capacity
-                  local wear = "N/A"
-                  if bat_info.watthour0 and bat_info.watthour4 then
-                      local l_full = tonumber(bat_info.watthour0)
-                      local design = tonumber(bat_info.watthour4)
-                      wear = math.floor(l_full / design * 100)
-                  end
+                local time = "∞"
+                if tonumber(bat_info.power0) >= 1 then
+                    local raw_time = bat_info.watthour3 / bat_info.power0
+                    local hours, hour_fraction = math.modf(raw_time)
+                    local minutes = math.floor(60 * hour_fraction)
+                    time = ("%d:%0.2d"):format(hours, minutes)
+                end
 
-                  -- dis-/charging rate as presented by battery
-                  local rate = bat_info.power0
+                -- calculate wear level from (last full / design) capacity
+                local wear = "N/A"
+                if bat_info.watthour0 and bat_info.watthour4 then
+                    local l_full = tonumber(bat_info.watthour0)
+                    local design = tonumber(bat_info.watthour4)
+                    wear = math.floor(l_full / design * 100)
+                end
 
-                  -- Pass the following arguments to callback function:
-                  --  * battery state symbol (↯, -, !, + or N/A)
-                  --  * remaining_capacity (in percent)
-                  --  * remaining_time, by battery
-                  --  * wear level (in percent)
-                  --  * present_rate (in Watts)
-                  callback{state, percent, time, wear, rate}
-              end })
+                -- dis-/charging rate as presented by battery
+                local rate = bat_info.power0
+
+                -- Pass the following arguments to callback function:
+                --  * battery state symbol (↯, -, !, + or N/A)
+                --  * remaining_capacity (in percent)
+                --  * remaining_time, by battery
+                --  * wear level (in percent)
+                --  * present_rate (in Watts)
+                callback{state, percent, time, wear, rate}
+            end)
     end }
```

Comment (McSinyx) [reply widgets/bat_openbsd.lua]: It seems that OpenBSD's sysctl outputs in the format of `variable=value` while the FreeBSD one is `variable: value`. Additionally, the current implementation of `bat_openbsd` is grepping for the last part of the variable name as key, which makes the code easier one eyes so I suppose we keep it this way, until there're more OpenBSD widget types making use of `sysctl`.

**Comment by McSinyx** [comment]
By looking at their Github activities, I suppose that both @Mic92 and @blueyed are currently/always busy working on other projects, so I'm merging this now, as it passes `luacheck` and no error occurred to anyone so far.

**Comment by blueyed** [comment]
This is huge, thanks!
